{
  osConfig,
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) mkIf mkEnableOption;

  cfg = config.wktlnix.programs.graphical.launchers.vicinae;

  inherit (config.lib.stylix) colors;
  inherit (osConfig.stylix) polarity;
in
{
  options.wktlnix.programs.graphical.launchers.vicinae = {
    enable = mkEnableOption "Whether to enable vicinae in the desktop environment.";
  };

  config = mkIf cfg.enable {
    programs.vicinae = {
      enable = true;
      package = pkgs.vicinae;

      systemd = {
        enable = true;
      };

      settings = {
        faviconService = "twenty";
        theme.name = "stylix";
      };

      themes.stylix = {
        meta = {
          name = "stylix";
          description = "theme generated by stylix";
          variant = if polarity == "either" then "light" else polarity;
        };
        colors = with colors.withHashtag; {
          core = {
            background = base00;
            foreground = base05;
            secondary_background = base01;
            border = base02;
            accent = base0D;
          };
          accents = {
            blue = base0D;
            green = base0B;
            magenta = base0E;
            orange = base09;
            purple = base0E;
            red = base08;
            yellow = base0A;
            cyan = base0C;
          };
          list.item = {
            selection = {
              background.name = base02;
              secondary_background = base03;
            };
            hover.background = base01;
          };
        };
      };

      extensions = [
        (config.lib.vicinae.mkRayCastExtension {
          name = "gif-search";
          rev = "4d417c2dfd86a5b2bea202d4a7b48d8eb3dbaeb1";
          sha256 = "sha256-G7il8T1L+P/2mXWJsb68n4BCbVKcrrtK8GnBNxzt73Q=";
        })
      ];
    };
  };
}
