# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  glow-yazi = {
    pname = "glow-yazi";
    version = "5ce76dc92ddd0dcef36e76c0986919fda3db3cf5";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "glow.yazi";
      rev = "5ce76dc92ddd0dcef36e76c0986919fda3db3cf5";
      fetchSubmodules = false;
      sha256 = "sha256-UljcrXXO5DZbufRfavBkiNV3IGUNct31RxCujRzC9D4=";
    };
    date = "2024-12-27";
  };
  mihomo-alpha = {
    pname = "mihomo-alpha";
    version = "ccc3f84da22dad5210ce2f7986c34198cc75a3dc";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "ccc3f84da22dad5210ce2f7986c34198cc75a3dc";
      fetchSubmodules = false;
      sha256 = "sha256-lTrUM4/t7GP8IhuyMqit7Iv4AX2I8tlMJWvgx2tDbgE=";
    };
    date = "2025-02-08";
  };
  miller-yazi = {
    pname = "miller-yazi";
    version = "40e02654725a9902b689114537626207cbf23436";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "miller.yazi";
      rev = "40e02654725a9902b689114537626207cbf23436";
      fetchSubmodules = false;
      sha256 = "sha256-GXZZ/vI52rSw573hoMmspnuzFoBXDLcA0fqjF76CdnY=";
    };
    date = "2024-08-28";
  };
  ouch-yazi = {
    pname = "ouch-yazi";
    version = "ce6fb75431b9d0d88efc6ae92e8a8ebb9bc1864a";
    src = fetchFromGitHub {
      owner = "ndtoan96";
      repo = "ouch.yazi";
      rev = "ce6fb75431b9d0d88efc6ae92e8a8ebb9bc1864a";
      fetchSubmodules = false;
      sha256 = "sha256-oUEUGgeVbljQICB43v9DeEM3XWMAKt3Ll11IcLCS/PA=";
    };
    date = "2025-01-31";
  };
  v2ray-rules-dat = {
    pname = "v2ray-rules-dat";
    version = "f22ea8ffd6eadf63e851456f26737033c4161d1e";
    src = fetchFromGitHub {
      owner = "Loyalsoldier";
      repo = "v2ray-rules-dat";
      rev = "f22ea8ffd6eadf63e851456f26737033c4161d1e";
      fetchSubmodules = false;
      sha256 = "sha256-+1T7c2d7wMWCb/l2VQE2YvXUZ000jpbuM54Qr8aEbVA=";
    };
    date = "2025-02-08";
  };
  waydroid_script = {
    pname = "waydroid_script";
    version = "3cfa1e43e7da4b0c07a4c83d331e4776012e2acd";
    src = fetchFromGitHub {
      owner = "huakim";
      repo = "waydroid_script";
      rev = "3cfa1e43e7da4b0c07a4c83d331e4776012e2acd";
      fetchSubmodules = false;
      sha256 = "sha256-O29v/lF2YCUhyCo+M7Sesoes0MObHsS2tutW88rOM/U=";
    };
    date = "2024-12-15";
  };
}
