# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  glow-yazi = {
    pname = "glow-yazi";
    version = "5ce76dc92ddd0dcef36e76c0986919fda3db3cf5";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "glow.yazi";
      rev = "5ce76dc92ddd0dcef36e76c0986919fda3db3cf5";
      fetchSubmodules = false;
      sha256 = "sha256-UljcrXXO5DZbufRfavBkiNV3IGUNct31RxCujRzC9D4=";
    };
    date = "2024-12-27";
  };
  mihomo-alpha = {
    pname = "mihomo-alpha";
    version = "0a5ea37c07b796ffe69baccb34edb480543902b7";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "0a5ea37c07b796ffe69baccb34edb480543902b7";
      fetchSubmodules = false;
      sha256 = "sha256-C/1i2OlgsbAYW7tZt/KcezJmLM2lOREXRRYq0RwlH3Y=";
    };
    date = "2025-02-04";
  };
  miller-yazi = {
    pname = "miller-yazi";
    version = "40e02654725a9902b689114537626207cbf23436";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "miller.yazi";
      rev = "40e02654725a9902b689114537626207cbf23436";
      fetchSubmodules = false;
      sha256 = "sha256-GXZZ/vI52rSw573hoMmspnuzFoBXDLcA0fqjF76CdnY=";
    };
    date = "2024-08-28";
  };
  ouch-yazi = {
    pname = "ouch-yazi";
    version = "ce6fb75431b9d0d88efc6ae92e8a8ebb9bc1864a";
    src = fetchFromGitHub {
      owner = "ndtoan96";
      repo = "ouch.yazi";
      rev = "ce6fb75431b9d0d88efc6ae92e8a8ebb9bc1864a";
      fetchSubmodules = false;
      sha256 = "sha256-oUEUGgeVbljQICB43v9DeEM3XWMAKt3Ll11IcLCS/PA=";
    };
    date = "2025-01-31";
  };
  v2ray-rules-dat = {
    pname = "v2ray-rules-dat";
    version = "5fed7c65fb628454838d02c743445d70316c71d6";
    src = fetchFromGitHub {
      owner = "Loyalsoldier";
      repo = "v2ray-rules-dat";
      rev = "5fed7c65fb628454838d02c743445d70316c71d6";
      fetchSubmodules = false;
      sha256 = "sha256-xqjaoGOTSvVPxX8PHOisNJmzPvzd1CIdyaiGEQhLXhc=";
    };
    date = "2025-02-03";
  };
  waydroid_script = {
    pname = "waydroid_script";
    version = "3cfa1e43e7da4b0c07a4c83d331e4776012e2acd";
    src = fetchFromGitHub {
      owner = "huakim";
      repo = "waydroid_script";
      rev = "3cfa1e43e7da4b0c07a4c83d331e4776012e2acd";
      fetchSubmodules = false;
      sha256 = "sha256-O29v/lF2YCUhyCo+M7Sesoes0MObHsS2tutW88rOM/U=";
    };
    date = "2024-12-15";
  };
}
