# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  glow-yazi = {
    pname = "glow-yazi";
    version = "c76bf4fb612079480d305fe6fe570bddfe4f99d3";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "glow.yazi";
      rev = "c76bf4fb612079480d305fe6fe570bddfe4f99d3";
      fetchSubmodules = false;
      sha256 = "sha256-DPud1Mfagl2z490f5L69ZPnZmVCa0ROXtFeDbEegBBU=";
    };
    date = "2025-02-23";
  };
  mihomo-alpha = {
    pname = "mihomo-alpha";
    version = "e23f40a56bb349545c6bd6ceac019c2b772df61d";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "e23f40a56bb349545c6bd6ceac019c2b772df61d";
      fetchSubmodules = false;
      sha256 = "sha256-BJK2ePQojw42FsKR9iZBmgiMJl3qPpqRWqKwjZA9tog=";
    };
    date = "2025-02-24";
  };
  miller-yazi = {
    pname = "miller-yazi";
    version = "40e02654725a9902b689114537626207cbf23436";
    src = fetchFromGitHub {
      owner = "Reledia";
      repo = "miller.yazi";
      rev = "40e02654725a9902b689114537626207cbf23436";
      fetchSubmodules = false;
      sha256 = "sha256-GXZZ/vI52rSw573hoMmspnuzFoBXDLcA0fqjF76CdnY=";
    };
    date = "2024-08-28";
  };
  ouch-yazi = {
    pname = "ouch-yazi";
    version = "ce6fb75431b9d0d88efc6ae92e8a8ebb9bc1864a";
    src = fetchFromGitHub {
      owner = "ndtoan96";
      repo = "ouch.yazi";
      rev = "ce6fb75431b9d0d88efc6ae92e8a8ebb9bc1864a";
      fetchSubmodules = false;
      sha256 = "sha256-oUEUGgeVbljQICB43v9DeEM3XWMAKt3Ll11IcLCS/PA=";
    };
    date = "2025-01-31";
  };
  v2ray-rules-dat = {
    pname = "v2ray-rules-dat";
    version = "c5d691c8bf31cb3b2186a1b4af8af819ec58b3c3";
    src = fetchFromGitHub {
      owner = "Loyalsoldier";
      repo = "v2ray-rules-dat";
      rev = "c5d691c8bf31cb3b2186a1b4af8af819ec58b3c3";
      fetchSubmodules = false;
      sha256 = "sha256-GwKwgB/6pCAIE/6FxFooo4JLMRrNQ3rigKa+LIPcqdE=";
    };
    date = "2025-02-23";
  };
  waydroid_script = {
    pname = "waydroid_script";
    version = "3cfa1e43e7da4b0c07a4c83d331e4776012e2acd";
    src = fetchFromGitHub {
      owner = "huakim";
      repo = "waydroid_script";
      rev = "3cfa1e43e7da4b0c07a4c83d331e4776012e2acd";
      fetchSubmodules = false;
      sha256 = "sha256-O29v/lF2YCUhyCo+M7Sesoes0MObHsS2tutW88rOM/U=";
    };
    date = "2024-12-15";
  };
}
