DEEPSEEK_API_KEY: ENC[AES256_GCM,data:kxTXu3H+Et1FzJVkx4BunuGb2ydbIrPkZfOSB/yBNuzwk1lEeweEzzAG4nN9lm9+V4a5,iv:fT9Q8k6JRBDrdiVvQIqF0C04AIvV3l5CNdoLlSP4MrM=,tag:4wxEFryyCDgpdDpwlwbIcA==,type:str]
codeium_key: ENC[AES256_GCM,data:whV3+m4KJjV6nXRNmCunQdnp/oCgD0w2EnblA3A+E2Lv67CdwOVXN9p82+Dgwwbza1Sx6g==,iv:xYT2jlbWFEKIvIH/mdSNPBGL9K/ywFCWV3DfK8+zxhM=,tag:Zqt5Wm5Bq9HyD+Tp5vB+4w==,type:str]
fittencode_key: ENC[AES256_GCM,data:UwRWVfZ1BawuLVQGRK9AG345u//ZMSvf26bLV+YDgoiHaA653kjy2QlwKybVFZQZwvUGRot/iwdS3M0Cr7bI4HgwIZ5BhvDmumB45c4OyiyGaoUO4A==,iv:BqpEX64pCw958iS2Kp34tLWPeKNxc2EUvZ1wfnpuLxk=,tag:6ye1F3NzIWCFvVztt/toEQ==,type:str]
cloudflare_dns_api_token: ENC[AES256_GCM,data:O4w8laIMergOky7eNkqTit66KTVC0GO1Je46ez/QQ6MRA8EHYDQWBg==,iv:X8QUTVi++LMMyh/qv+p8bmre8mp0nP8/dOdBnkzsN8g=,tag:+OaWhfD+ou1deE98zcbI9w==,type:str]
wireless: ENC[AES256_GCM,data:187ZQyhrjCYgVxz0+T7m1R72UcqxRVfp+jFsUF+h0A==,iv:nVnMGzdvjgpWiE5KxGZfu8ihwYPDpSQDpdWWvl30KSY=,tag:Q8XSHLMwtKRUAQfjt7wEQQ==,type:str]
sops_keys: ENC[AES256_GCM,data:Cfpx/W0GoL5iepl2dBM6aof0psM/cR0dqULxaFLgM/yo8IN9C8BD/R0qhwHExuMCqgjO7H6I0ytj32o0RTOUuxjt0iMiHIGvHDKa5MEniB/vmmofBS3j7ZKgEt0EQgantTsWWkQI7UHP0QEhYqcdqJuMzDR3uXXU8CMXzoR3BlbQQ7ZcWjF94hPIUb54MyCY7Po9QNLg6MnAp7+ylsIk00veC4wHCZbkvEZ7NV+ZeXeIffldoixyK1SKHTVK97LZVRgudbmJkwN38v5wxdVNyfxaUQD6JEP/bMqUn6xDbcWKcM6aJRdyIJaRUpoB58/q9YU2izR0HVV71dat2rH4UNcV0diN1fYInj3Kh3/mkrXhaea1btM13PxEPCfwTHXzEDHgG7Mp6ibDD42o2RHAoipiKZuzufftcnq9sI3OW1psnw0qw1ZrWqvNOAfO3M9TCIh36OAcj7BtmdKAI4KLDEpBflsXWYlojgE7rR9Z2O6YiAd0EAwMiscYb4BwHbN5CbGggt1ug/ShwY7FZnwfeoLYldrGqkeyErPAa38Kx3h/v4NiwkqHF+V2Ad0rAk6sTwF652XFKUYA+k0=,iv:soNM8dfhnfTbavxHR7iC5tSxLoFBuOmi+xq9GyOiKks=,tag:W9N0obpVCC6fw3qixjWM8w==,type:str]
dae_nodes: ENC[AES256_GCM,data:Qtkl1bXfCtswflRSPkhvwTXzSTA5fWe4ypW4FWEOozk5QCjjHmymHsR+cfdFPzPHe8EzuCJP+zMfbFmS5ugHOSpKE96LQ32aBgodZz6gPAkShbW0o672Lm80B71tiyqyIPjxaCBbMxJzqzwCqdoQnGoaRzS8R7QzRn3K54IFDo4z16YxQjls0MsbkAlVRWxTXZFENaOKRBVcNNw23XeWPqFD1PefjB5QJXOP3S4Zv8QaZgHp42Jg570ZPchzSTQY3m/F70QkHzskez/O3gF5t7GpjuQTGkLNsqW0IF75WZF/J7u0bRtUG/IWYtZJByJyakupKOK/gDNsfpQLFDTvdVnS78uOFFI3D/yp65wdoDpjnYINyfOJFkaituNQLpMzB6Pykg3wRMg86qLqY+Z2nVfIY4oXIAmfGnv+HeODgJmplLDJOtgxDnaybr7YQJN0mNUm0c0U31g4eWgsgXPZnB0yrFGW/sQrMubsoLC3AHPFWddd+RyUBxebaNi6Qb20XJYW33rNi5XL/ZNYjdP/4ZEvhNyhYTrtzCe8jv2XkKmyUIwUHVoOIX5iz6nqEpXb/nGWAMH45m0FyMZlE3txOyx1mbfoLe0KdXc+xg==,iv:FqZZgdKz6uPsqfpvl4TseHoJQTadl5t/Zts6y4MjUWI=,tag:+WPLzzDmWIbKuNzm6X2U6A==,type:str]
milet_sing: ENC[AES256_GCM,data:AI2QhkGwcFqrV5aOlC/PWpg7vN5CHdTh9XeqB9LWt+WcWccYyY1+wyYis79pHIjwqguyuFPv/2Va8shwVGqw6HHUyKLBw1e/bJt8EFK9ppj67bH8QR7edTgHS9Jat4lMS8NGZn63lBeboeWr8CUanZ9q+mO5BgAse7P5yKjEDL4Obu/JPAJOBOLmuk/3SF4F1hhn11n7HS1mZyGGhf13iZO365ztBq9WiPRsqNh8gnaZfL5VQEDlFcm4zyY9Pp7eDJetHdB5Ty6boNAEhMc0Y6mIgWj1GBJhcOL2l+Puq0Hfllhd2ns6GEI85mGxNeR2LnBtUWZuPZfZQhb2ziSvliaTMZ2qms/VpRFj9p2/2lMcAFSE2UIU+rw6dfkn6EJktp5sur5uqyjAWG9yX9cXcU+jymsohIsdDv+Sa0on1WSwb1zIj7l1ytbd6h6bNUTaXDa0qcwon7OSOjO38w4Wsph8Bj+c4Hi+KBBmP/2lTo2t1DhwvuBD4q5qtZZ0j9qyOiHhYCSLLEmxGxmaMwp66C38kxqkmS6hQvwK8q8ergeIvpplKSy8Ur6Dn2Ni/scD3sk/B4Btr53CiGATqyXFpN9XPhM4xrpGUILHdtq8tGy5qmrGSV6pfwAn95yaYqkSe2KWsM0cSwpc4m+/KWAl4h1scT++t4A0HbH6jDeKFOCYuEq0jC09Bv7wY6KW42g3Bjc/uTxc5sPw/hJP85V5XjZOP7xlmjNdnp4LZ+4hlt4yiI39GFRgxQ1dyTVGk88icEeP4obyd6Y6X3UFNPLbySzLbqg5AJX4g3lEYTIvsXIkhjV2BzGfdX+CuPffdhS4aeiA+9KxiTXUP7nFQK6M1N1dzoMu5TsakdGWaa9IdLt1GM9mHcDM/Pqyp8b76OjKQTVhIFsdbDA5JBbGhrNbYQz/Tkn28Ep2hLKnvu85gzQW1zia1UK5YSDiOn7FZ+yOJrUUlgXDPR60LFIrHfNRPXabXoPWH/oBFA==,iv:gLJD74MqDVsuiExOrajyU5ZoKzjgsmsY1J1FVPDUZkM=,tag:ThXLrzrfPVN2Bf01RGqxLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ay9wumxmumd7gx9kwz7vzvgmh6l3qyxj6jka4y58rucnzrckgssss8jzdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRFFUL1NYMkw1NnFmQnBN
            em5Ed2dIOXJYQlJjd05acDZ3SkZtcHFLZDJFCjVTVUlxd0dUcWhhejlISnFSS3BD
            RGhZSHdkRWVsZnJLbFZqSUNWSGNheTgKLS0tIHluREp6eGNEb1hiejRGTVNmMVZY
            VTMzaU9RRVV0Y2NYb0diQndRcldDSVUKj+R/hBimHOAvDZO0hraEdses01bRK5P+
            wgH3FqL+XR2O/gk7LgCXG4fwPa/61bP6rGfM+J9QCXl0h2rQJR1XYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zhg38324c6uaexfdhgermpsgwk2ll6795qn0n9j2pxula94yr36qaqfph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VGJMd2VZUkJCTmZBVUh4
            enhGN3grNE9aWjhnUUJPSW1lS3d1N3pVWUZVCnB2OXVZcUxVQnZ2R1ZSS2lxK1hK
            QW5SbDU2anFVOUR5STk2bVVJYjZIRUEKLS0tIFZkS0s5R3ZtQnNLRjhYV0xMUGRm
            ekxhZzNHWE84TGdyMjB0ZHRXbGdnRlEKogJdg5H1RkOvlJGEvOwkrmJ7ZdsKYY75
            Ji/tF2NaQSjxRsKQ+rfY+WR63iu5PywiNwaKmJoAprPKtCB8lQka+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ag79ucstq460ysr78e2d78vkgg5tl2sq8r6wpa2kvmf5x2qh5s6szupsa0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV0VRUSt0eTdsUTFvVkZ5
            UmZLRmlCQTloa1hXYlhCdTU0d29zWkdOekQ4CmVKRjJYYXgwQW9qRzc0WURaSXht
            UXBjeDVlejdmeHlvN09sQjdMeldISGcKLS0tIDZ0NVVwY1JZdjdwNXJmaTRBZW9q
            YlFOcU81djlGYmZqQVYzeUZzaU84ZGsK3DNUIdzYPWNc+DJzUcfP4M6v3pa7LftQ
            Xa7l8TyrcQVlk1yy+WpQMOtJ8b6OjKTnQ+3gT5gupSy7f4TswU6nkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ug0s0wd45s7c8zleahzsrkxdprwz9sssrqyyhre6jljzhykt7qeqctxkt0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRVNETHB0NWZieE93TkFl
            WmFqWm8yTHdEU2VMNUFoNm0xWE41c05xdXdNCmxnczJyLzU4OTJSUkRFZ2tDYzg1
            UmR5SzJHNm15QTJLSmNLU0xkMmhDVmcKLS0tIDlpejNBY3lXdDR5MG1IcVZrZFAz
            NklxRDI4Smg3M1FNZGJJcC9VVGhiaEUKRtwa0GQWjVQnHc18POcjDKcKyHJDAVzL
            y+07QDNUiNG2m2Rq6C43RxavLHjmTVtzhBqfh1jRHd6owiOG8jkdkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rrpde8u95jscps6uyc6as6r05qanxhw2cpm5tfgc5p2gjmu5u49qqpa9c9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU1BtMGRDY3Vaekd6R3I0
            V3A2amZpdG4rTUQ2N0lBWjJPN0lzbURJSWhNCnRqc3E2QTBxNVdCVWJYSThWWjk4
            cDBpV2RzNUlDREdNMEV1VUdLUjE2dzgKLS0tIFBJREJKUkt6cjRMUjRzOWJnNk41
            cWV1R1U4RUV4VzJOV21SWnBlMUltUVEKfhG4AqmFSAQm1m9tnblrEmv8ROE21FwW
            uwY1gYSsWQcAAerGA9SJID+gGxuiBkvEFhuz2xoz7iNDA5+OzBwdyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-26T14:12:31Z"
    mac: ENC[AES256_GCM,data:GZwlV/k3sPJDXfcB2VdS5dysg0rxU3FwtJlEKiyAojHZujqpxDpDFSE6w8772wwiU5GP0XWnXxP7BsJ1blr5SasvgCC87REN7zh+PKW071LU9NqmiNU1Mfsc6Wva4axNajT+wpR+4QQGtQBd4bobUWHdhYDwejYj+WBEgUQ+LmI=,iv:SbC7bh6mYzHGylzQz2ts+4pRi1GWtXVlEUOouqFrCus=,tag:VhPy86vAZKGnKB4l2grBNw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
