aria2:
    - rpc_token: ENC[AES256_GCM,data:8+dtSKfwWem18n8=,iv:z5ILPF+tiK3HUkMkU97ObpNyFfMcDPEfb+GcIKzZWA8=,tag:CkiGmQ+W826zwt/jCSMIPA==,type:str]
codeium_key: ENC[AES256_GCM,data:whV3+m4KJjV6nXRNmCunQdnp/oCgD0w2EnblA3A+E2Lv67CdwOVXN9p82+Dgwwbza1Sx6g==,iv:xYT2jlbWFEKIvIH/mdSNPBGL9K/ywFCWV3DfK8+zxhM=,tag:Zqt5Wm5Bq9HyD+Tp5vB+4w==,type:str]
fittencode_key: ENC[AES256_GCM,data:UwRWVfZ1BawuLVQGRK9AG345u//ZMSvf26bLV+YDgoiHaA653kjy2QlwKybVFZQZwvUGRot/iwdS3M0Cr7bI4HgwIZ5BhvDmumB45c4OyiyGaoUO4A==,iv:BqpEX64pCw958iS2Kp34tLWPeKNxc2EUvZ1wfnpuLxk=,tag:6ye1F3NzIWCFvVztt/toEQ==,type:str]
cloudflare_dns_api_token: ENC[AES256_GCM,data:O4w8laIMergOky7eNkqTit66KTVC0GO1Je46ez/QQ6MRA8EHYDQWBg==,iv:X8QUTVi++LMMyh/qv+p8bmre8mp0nP8/dOdBnkzsN8g=,tag:+OaWhfD+ou1deE98zcbI9w==,type:str]
wireless: ENC[AES256_GCM,data:187ZQyhrjCYgVxz0+T7m1R72UcqxRVfp+jFsUF+h0A==,iv:nVnMGzdvjgpWiE5KxGZfu8ihwYPDpSQDpdWWvl30KSY=,tag:Q8XSHLMwtKRUAQfjt7wEQQ==,type:str]
sops_keys: ENC[AES256_GCM,data:Cfpx/W0GoL5iepl2dBM6aof0psM/cR0dqULxaFLgM/yo8IN9C8BD/R0qhwHExuMCqgjO7H6I0ytj32o0RTOUuxjt0iMiHIGvHDKa5MEniB/vmmofBS3j7ZKgEt0EQgantTsWWkQI7UHP0QEhYqcdqJuMzDR3uXXU8CMXzoR3BlbQQ7ZcWjF94hPIUb54MyCY7Po9QNLg6MnAp7+ylsIk00veC4wHCZbkvEZ7NV+ZeXeIffldoixyK1SKHTVK97LZVRgudbmJkwN38v5wxdVNyfxaUQD6JEP/bMqUn6xDbcWKcM6aJRdyIJaRUpoB58/q9YU2izR0HVV71dat2rH4UNcV0diN1fYInj3Kh3/mkrXhaea1btM13PxEPCfwTHXzEDHgG7Mp6ibDD42o2RHAoipiKZuzufftcnq9sI3OW1psnw0qw1ZrWqvNOAfO3M9TCIh36OAcj7BtmdKAI4KLDEpBflsXWYlojgE7rR9Z2O6YiAd0EAwMiscYb4BwHbN5CbGggt1ug/ShwY7FZnwfeoLYldrGqkeyErPAa38Kx3h/v4NiwkqHF+V2Ad0rAk6sTwF652XFKUYA+k0=,iv:soNM8dfhnfTbavxHR7iC5tSxLoFBuOmi+xq9GyOiKks=,tag:W9N0obpVCC6fw3qixjWM8w==,type:str]
mihomo_secret: ENC[AES256_GCM,data:eOPSy7i5/nLzNfc=,iv:p14ba7L6W7Od56WY/2C4MIKR+iOsEWdWdOU+OsUfy5o=,tag:7TDDj//VxfrW3DpNuUGc+A==,type:str]
mihomo_nodes: ENC[AES256_GCM,data:10iHgYvoy+2+E6rdj1EGo3/WVjsis6S6mpJur5zvveMh75f55aphe/0owArfwvBjHzRaSSFvZDSXOpdC7JG17Gmo7eyhORiJAsjlLsQ8CKMUi6282YjrP9Q2ih4pGs8T99uXVZfROi1cY3oXAzPgB93OTG2I/yf/0IEkOqxP/p85GRXBgHhVlUS0DSDFmqtOuoeDN1nxW91r9nboe5vn9tHAiLnLMW6j0ePm/ehr4IF6uUFXN4GkOYtJd9SHwIhzGU5uk2cBKAmlV/7j6abiNbCQLmSHIxAyIuUxxYVJpA9Fc0qILEHLC5Do8wjBaSNaD12F9ru6yoSWcP4PEUE0RQiiikjrbwBo8gWbbjPipnmUvpAkDvjJxapxV+lhDdgL/wgrf/kZHbU/z9pASOPl7Hy6JLDa3zX2+EBsXIKCkgC73PfvBeyQGnRf7lK9/Zu9Qd379JDBvUuRKx9hNzOKhNJxRy40nC+asa4698y6SRx8K8bCP3FhyrTqcvqFyVySiQluOWxJRnCEWJDxp4n5VFk3Qik=,iv:o5xf1t1plQrP+iZiD2LYZLmngVTgl9qd/YXe+dF9rdw=,tag:WOm+f24ujzED3CygWtXZnQ==,type:str]
dae_nodes: ENC[AES256_GCM,data:jFMX5BD77eqnSsYi6PPGjvjGBjDsANEXw9yCodFfDmvvs4YaRPRWDvq5RkqDNDM0ubhLfecgnBZbdeKvmatU6KNYDDdhrniv72nz6UzgjMvdLjgPbr72Ne/1rhzVO6cU0nys+2YopKvMpGA/5WH9ILwXKox9x8Ww21NRONvAUodaYbzGvbTq5pRf2n1aJqvmBWRXYorfwcNXCStSmq8eq74oVIRVoJd1m5WE1WuMpSpVn7QInP0yaz+JikM40aux2VQ16tWZEzx/mot/CDyf1VlSi8N6BT00V7nJF/dNpqEsy9ZFRM/wwTZm,iv:OHaP4HDpdLZlCqAq2UwJHdawmwBBGLUkuvyHwlJ/+4M=,tag:BFSRbwaE39JZXRBSxjNOIQ==,type:str]
DEEPSEEK_API_KEY: ENC[AES256_GCM,data:kxTXu3H+Et1FzJVkx4BunuGb2ydbIrPkZfOSB/yBNuzwk1lEeweEzzAG4nN9lm9+V4a5,iv:fT9Q8k6JRBDrdiVvQIqF0C04AIvV3l5CNdoLlSP4MrM=,tag:4wxEFryyCDgpdDpwlwbIcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ay9wumxmumd7gx9kwz7vzvgmh6l3qyxj6jka4y58rucnzrckgssss8jzdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRFFUL1NYMkw1NnFmQnBN
            em5Ed2dIOXJYQlJjd05acDZ3SkZtcHFLZDJFCjVTVUlxd0dUcWhhejlISnFSS3BD
            RGhZSHdkRWVsZnJLbFZqSUNWSGNheTgKLS0tIHluREp6eGNEb1hiejRGTVNmMVZY
            VTMzaU9RRVV0Y2NYb0diQndRcldDSVUKj+R/hBimHOAvDZO0hraEdses01bRK5P+
            wgH3FqL+XR2O/gk7LgCXG4fwPa/61bP6rGfM+J9QCXl0h2rQJR1XYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zhg38324c6uaexfdhgermpsgwk2ll6795qn0n9j2pxula94yr36qaqfph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VGJMd2VZUkJCTmZBVUh4
            enhGN3grNE9aWjhnUUJPSW1lS3d1N3pVWUZVCnB2OXVZcUxVQnZ2R1ZSS2lxK1hK
            QW5SbDU2anFVOUR5STk2bVVJYjZIRUEKLS0tIFZkS0s5R3ZtQnNLRjhYV0xMUGRm
            ekxhZzNHWE84TGdyMjB0ZHRXbGdnRlEKogJdg5H1RkOvlJGEvOwkrmJ7ZdsKYY75
            Ji/tF2NaQSjxRsKQ+rfY+WR63iu5PywiNwaKmJoAprPKtCB8lQka+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ag79ucstq460ysr78e2d78vkgg5tl2sq8r6wpa2kvmf5x2qh5s6szupsa0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV0VRUSt0eTdsUTFvVkZ5
            UmZLRmlCQTloa1hXYlhCdTU0d29zWkdOekQ4CmVKRjJYYXgwQW9qRzc0WURaSXht
            UXBjeDVlejdmeHlvN09sQjdMeldISGcKLS0tIDZ0NVVwY1JZdjdwNXJmaTRBZW9q
            YlFOcU81djlGYmZqQVYzeUZzaU84ZGsK3DNUIdzYPWNc+DJzUcfP4M6v3pa7LftQ
            Xa7l8TyrcQVlk1yy+WpQMOtJ8b6OjKTnQ+3gT5gupSy7f4TswU6nkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ug0s0wd45s7c8zleahzsrkxdprwz9sssrqyyhre6jljzhykt7qeqctxkt0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRVNETHB0NWZieE93TkFl
            WmFqWm8yTHdEU2VMNUFoNm0xWE41c05xdXdNCmxnczJyLzU4OTJSUkRFZ2tDYzg1
            UmR5SzJHNm15QTJLSmNLU0xkMmhDVmcKLS0tIDlpejNBY3lXdDR5MG1IcVZrZFAz
            NklxRDI4Smg3M1FNZGJJcC9VVGhiaEUKRtwa0GQWjVQnHc18POcjDKcKyHJDAVzL
            y+07QDNUiNG2m2Rq6C43RxavLHjmTVtzhBqfh1jRHd6owiOG8jkdkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rrpde8u95jscps6uyc6as6r05qanxhw2cpm5tfgc5p2gjmu5u49qqpa9c9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU1BtMGRDY3Vaekd6R3I0
            V3A2amZpdG4rTUQ2N0lBWjJPN0lzbURJSWhNCnRqc3E2QTBxNVdCVWJYSThWWjk4
            cDBpV2RzNUlDREdNMEV1VUdLUjE2dzgKLS0tIFBJREJKUkt6cjRMUjRzOWJnNk41
            cWV1R1U4RUV4VzJOV21SWnBlMUltUVEKfhG4AqmFSAQm1m9tnblrEmv8ROE21FwW
            uwY1gYSsWQcAAerGA9SJID+gGxuiBkvEFhuz2xoz7iNDA5+OzBwdyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T16:17:55Z"
    mac: ENC[AES256_GCM,data:u/VcuLSBGbTGiJlCjmtMJJVt5pSZNNwwyvG4WRLDdTTiosGim0Ja8MUzto2dDUIQYbsSBfGe8y2IkRWt4+xdflbT2Tgn4aLQ+2C6mSebJuBhgnKK7+IrtsGuyCEbd1IGlkZlaGo2j+XdXUXypAolv+1YFuMN4BQKUhQV1QNABy0=,iv:AJrHEzGtHnLpZMjxIqdzQXyefem9aY8W/ZQ/zhsJID4=,tag:tM9isbwoZY+FqPKuWF+Jtw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
