aria2:
    - rpc_token: ENC[AES256_GCM,data:8+dtSKfwWem18n8=,iv:z5ILPF+tiK3HUkMkU97ObpNyFfMcDPEfb+GcIKzZWA8=,tag:CkiGmQ+W826zwt/jCSMIPA==,type:str]
codeium_key: ENC[AES256_GCM,data:whV3+m4KJjV6nXRNmCunQdnp/oCgD0w2EnblA3A+E2Lv67CdwOVXN9p82+Dgwwbza1Sx6g==,iv:xYT2jlbWFEKIvIH/mdSNPBGL9K/ywFCWV3DfK8+zxhM=,tag:Zqt5Wm5Bq9HyD+Tp5vB+4w==,type:str]
cloudflare_dns_api_token: ENC[AES256_GCM,data:O4w8laIMergOky7eNkqTit66KTVC0GO1Je46ez/QQ6MRA8EHYDQWBg==,iv:X8QUTVi++LMMyh/qv+p8bmre8mp0nP8/dOdBnkzsN8g=,tag:+OaWhfD+ou1deE98zcbI9w==,type:str]
wireless: ENC[AES256_GCM,data:187ZQyhrjCYgVxz0+T7m1R72UcqxRVfp+jFsUF+h0A==,iv:nVnMGzdvjgpWiE5KxGZfu8ihwYPDpSQDpdWWvl30KSY=,tag:Q8XSHLMwtKRUAQfjt7wEQQ==,type:str]
sops_keys: ENC[AES256_GCM,data:BYpXEH4hTUWkcUO0au0CWT7d87c2f79AMTGEjJBeZBfiLFknhocDO/FrXffIfZVEgJr1hq3IDzAcQF/jmb4kMpm937eKB8B63X382JVihGszqTk55p8kaZ0TWy5HARaVwmercrDFqxWE+iLD/lCP2ZjzBWiCCtgWDS52s971jLXv3rs+iOJV5Nut2I5wECKDxSPtCbgQZOVxcmAEnicOHeHnd/VT6Fom7rcUMcKZan0XttDnTAf65l6d49WKsMOksiGN6/W8o+jkDxrokKJalUORJUMbV4PfrDRhO6mb8FLETQhMeNOFcS0vunBH09xO0zOhYiJKVDRd1ohB+pGKhyHTsmVIGbFvJXZ+JFQ2HcvqC0KCFDeGtFAuDZ4JtkaJMarVPlcZx4kQkgvNQJ53NJ5SauIRAB+Hv5IhtWPK0cDFwBA4J0DcaCvNBdcMXY4sVJP39bWH1kVPjgxAcPc=,iv:4NBLfFT/JczzNDxeGlL1oCB4ZzIvgz6VA1yU0wbdxMA=,tag:h7WnWF7xiqnH+TU8eVPx0Q==,type:str]
mihomo_secret: ENC[AES256_GCM,data:eOPSy7i5/nLzNfc=,iv:p14ba7L6W7Od56WY/2C4MIKR+iOsEWdWdOU+OsUfy5o=,tag:7TDDj//VxfrW3DpNuUGc+A==,type:str]
mihomo_nodes: ENC[AES256_GCM,data:10iHgYvoy+2+E6rdj1EGo3/WVjsis6S6mpJur5zvveMh75f55aphe/0owArfwvBjHzRaSSFvZDSXOpdC7JG17Gmo7eyhORiJAsjlLsQ8CKMUi6282YjrP9Q2ih4pGs8T99uXVZfROi1cY3oXAzPgB93OTG2I/yf/0IEkOqxP/p85GRXBgHhVlUS0DSDFmqtOuoeDN1nxW91r9nboe5vn9tHAiLnLMW6j0ePm/ehr4IF6uUFXN4GkOYtJd9SHwIhzGU5uk2cBKAmlV/7j6abiNbCQLmSHIxAyIuUxxYVJpA9Fc0qILEHLC5Do8wjBaSNaD12F9ru6yoSWcP4PEUE0RQiiikjrbwBo8gWbbjPipnmUvpAkDvjJxapxV+lhDdgL/wgrf/kZHbU/z9pASOPl7Hy6JLDa3zX2+EBsXIKCkgC73PfvBeyQGnRf7lK9/Zu9Qd379JDBvUuRKx9hNzOKhNJxRy40nC+asa4698y6SRx8K8bCP3FhyrTqcvqFyVySiQluOWxJRnCEWJDxp4n5VFk3Qik=,iv:o5xf1t1plQrP+iZiD2LYZLmngVTgl9qd/YXe+dF9rdw=,tag:WOm+f24ujzED3CygWtXZnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ay9wumxmumd7gx9kwz7vzvgmh6l3qyxj6jka4y58rucnzrckgssss8jzdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR1ZhNk1uL3dOTjdWc1dh
            VlV0WWR5ZktFZUdhazZhU1ozeDBodTBwUlNjCjJBS1NBVXBtQ0ZaaGIyd1dtWmpS
            YU1jMWNYRFlaMEhVT2RHZnptcXZPa28KLS0tIHNiTjUwemtDaDdUcDkvSXk0c0J3
            YnR4c0QwM3ljdjQveVhFZjVDeHlPRGMKCIZdYGu1EmgEqozENXg+fTjNZBd2jEUe
            DGKOjKwe0tOTuZ4Q1zm9gDdC66dhC2ObpSlOOYwAO15pco6S2ej5yA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zhg38324c6uaexfdhgermpsgwk2ll6795qn0n9j2pxula94yr36qaqfph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQ3FITWczdVJ3dVJmVHI0
            Qm03eTVWUDhNeDlBOEIxZ051c1Z1NnNEaUcwCnV2Q05jQWUvMGd6U2I5OVVZcXdo
            azJabjIwTkhMcWtTWmdTaFJmTkNsYkEKLS0tIGVUcmlzM3RDdTJtTUl6NEJDS0kw
            d3RBazRGdmRBNEwxTWVFR1Vqa1VlczQKnkdH+nmPvzkvCqWa8coKUZNSucB6n1ij
            MJMPcE5twQh9ousznJ+Z53/eS0ZtpBiaplI+o2zBTWEztitIfBCC/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ag79ucstq460ysr78e2d78vkgg5tl2sq8r6wpa2kvmf5x2qh5s6szupsa0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMY296UkRSK0hJYklZWXg5
            WEY4enpWb2hHTHZrWE9kKzhTeWhtSlZEM2tjCmZTdEtwVGJtYS9pQm95RFdCbG9q
            bVUwd0w0MmRIRDBqdm9YL3Y2R2RtVU0KLS0tIDFvQ1d3aHhiRlpiR0U4RFJpR2tO
            QnVqWW9KTlMvNUVKWnFrZzc5Z2xabTgKGesrEw+Lz3XlW7H5W7C/+kPyBXO+2EP4
            u09NcLyxoufAKYGJVJOqBIcTXWe85opmXzsYv/Q/Ga0EjXUPr21c8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rrpde8u95jscps6uyc6as6r05qanxhw2cpm5tfgc5p2gjmu5u49qqpa9c9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTDFWK01jWFg2eU02cENq
            eGh3d0RtOHBPRE0zWWoxSTJvZzR3TFJmZGdFCktsd1JsdlJNMDgwRlVxaUxKTzB1
            RU84aVQydjdhM3Z3M0NDdjBhVjdwc3MKLS0tIEkzK3N1WUpTQU5qZHZnbU50WTdL
            eUJxMDY4UDhuakhSNFVZc09xYnlCTUkKuAVKgWfpOE2XK9hm1MDYKsWM/t57HU3W
            hS0yzoW17CQNmvJyQV5O+qKSaEdWYCGPRQwwo7fzbMsH2WwcJLBPTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T07:28:42Z"
    mac: ENC[AES256_GCM,data:1R/WoaGQwfPvxq1xwMublYSRRNEznW/v/4G8dBHDe/8xxF5bSI8wZpfuqhpTIvelryjqskmP+MbsgINhvfq86/p5EdERxLXWOt9P5b4dKXc7c3n8O1N4eMoWwt/a5uvhn8H9JViguz7WceXbCXYVRU1ymlwBdf6BoBNbAeovu3k=,iv:xR2SJVhONYYhWxAweql8DiHbSil6yZ7Q/wrlTp0Q/BQ=,tag:iwJrXuPBX6qi7wzFPj9cpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
