aria2:
    - rpc_token: ENC[AES256_GCM,data:8+dtSKfwWem18n8=,iv:z5ILPF+tiK3HUkMkU97ObpNyFfMcDPEfb+GcIKzZWA8=,tag:CkiGmQ+W826zwt/jCSMIPA==,type:str]
codeium_key: ENC[AES256_GCM,data:whV3+m4KJjV6nXRNmCunQdnp/oCgD0w2EnblA3A+E2Lv67CdwOVXN9p82+Dgwwbza1Sx6g==,iv:xYT2jlbWFEKIvIH/mdSNPBGL9K/ywFCWV3DfK8+zxhM=,tag:Zqt5Wm5Bq9HyD+Tp5vB+4w==,type:str]
cloudflare_dns_api_token: ENC[AES256_GCM,data:O4w8laIMergOky7eNkqTit66KTVC0GO1Je46ez/QQ6MRA8EHYDQWBg==,iv:X8QUTVi++LMMyh/qv+p8bmre8mp0nP8/dOdBnkzsN8g=,tag:+OaWhfD+ou1deE98zcbI9w==,type:str]
wireless: ENC[AES256_GCM,data:187ZQyhrjCYgVxz0+T7m1R72UcqxRVfp+jFsUF+h0A==,iv:nVnMGzdvjgpWiE5KxGZfu8ihwYPDpSQDpdWWvl30KSY=,tag:Q8XSHLMwtKRUAQfjt7wEQQ==,type:str]
sops_keys: ENC[AES256_GCM,data:/E3MaIYGDBaU9xKrYiWnPU6JOel/agd2erWJH2CNF1E3RNX53VyRS/EYGNi9HzVg21FDVhcfOshwP3y4F4kspwhIeTOi5yzQP+RGYkZN1uYXpcPH/Hczc1+Na+/mDsYgbv18OvCEYVAsQ7vvEYiQ72fhSrAtCZU2gA27SMSQyxBQ0RdyLnHdp01rFzNDk7Pg8OGCqKXxc4aOhpPHQdqUsqEo5qDSvlKoSy8JYSKuC/jTwWydGM7IselQMr0nm8iGmnMlSzFlbZ1cLz8pxqk9fwOPUct6/kuL+idXSun10+fO+DiDvHjD0BX/V2ZHUdsjk0JcW+BpaNsPYy9F7d4wyvBhSMlNgm4SRsmJ9J8WbvTtCkoIcjPLT3wq/gTf/5kyyqGEJ6rQqkbU9ZhNgRllc64R/5FjWZo1kDLjOt/T6aLFTrgzN6M9nr6w,iv:wK9+YPl5jRsdq4IBlakLpcZ0608VhWk4oOghonlraMg=,tag:jgEQezETPD8tt2eZEnEB9g==,type:str]
mihomo_secret: ENC[AES256_GCM,data:eOPSy7i5/nLzNfc=,iv:p14ba7L6W7Od56WY/2C4MIKR+iOsEWdWdOU+OsUfy5o=,tag:7TDDj//VxfrW3DpNuUGc+A==,type:str]
mihomo_nodes: ENC[AES256_GCM,data:Yg1dS6Es5loXlQPTF7jJUnSoWVa4USGt8OXOvhVegkRLBDfPQiE7P49gAG51469LUtdCYYz9cnfumsOKEVLbN9/UFbcd9QAxP2hmNmyAG77WJZjTRZdYV4xl0YNGYd5olEXpDtPQnou9eJVQouqTPLe2GSHcPWj1aAErPSrQ3pwQBeKEbPXv32vyYo9dNrxgGn3JasmfMiOsQd3ZZZYrN2wh4PGDjTB8aWjdsuwsrry2oPlJDq9BmOnQxuComlcwiacUOybOvEfHo9bSoM0YCnhf563Gz3rvE4ye3rAKdmmjhlthfiHMyR8qSYAfFQkU+IdRZczGBwzn+FeQ8jsltL2VEtpWWJ4vrlzYtmufEcxu+xtJfaEnng1Xh43oTiQ3G+OsoHVh8216ZNWPVHpDROdVOkpH9FhktneGB54gKxwaco/pIy0sHswLQq87Px3n5dqa8elJ+EZDHPxGzfWupW5Fccmw9wVSKEkPi7Rqz1Eh5RuPr6MVwuvZRbnCnlinzrRBj8oE6WuZaUfrFBS/Adw5ak2M0g==,iv:ZwcWuiYQwyx6KnLJ14nRGwgCpuMRvF6Y/+tDhSrZzb8=,tag:MssjJcbxN1L4T/OKhBtuKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ay9wumxmumd7gx9kwz7vzvgmh6l3qyxj6jka4y58rucnzrckgssss8jzdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNGtBUnBrVWhkMGw4V2N0
            VVE2UDJCYjlRdjlKWUdpMEZDNFhFK3o5cFVNCk5KdFRIUFZmVXJTeGFHaHB5Uy92
            dUozNi8wYlk5aG1KSHMycnBmTnlMSW8KLS0tIHlVczI0MmNvR1lNRnIweGJ6RnJx
            SFpadjBKM3RSUEx4TlQ1bG04MWMvVncK0MLL7QNBg4YpxtWbJjTk/4MqTOp84C9A
            cIize+au97PFQd4fQNRpy/Z2QHde7uW2gD9q+7eDvZh3yuACll7McQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rrpde8u95jscps6uyc6as6r05qanxhw2cpm5tfgc5p2gjmu5u49qqpa9c9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZFdGNEN4Yy9mcHhwTGpO
            TGtXQUdrczNwQTYrNFJKSzBiam1rRUhaTGlVCldrVlMrcjdpR2NFWlNvcGlldG1M
            SFdZMTNuL08vYkhMTmdoYmlzN3dWRzAKLS0tIHI1MVU5a09oT3BGQVprdFlTbzEy
            SmNyM2FVRlo4ZnRuaW51UU4wdjd4ZnMKxjP/jZNNziW+WwdBZsy84nCU8KKw4ER0
            YVA7ayNszlbqEJplMwcjQK+zMvkKGYN2lzef2gqeoxJ4PeELJk7MDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T10:44:13Z"
    mac: ENC[AES256_GCM,data:mvV+2d2peLownLYN8UlxIAicyhMgTUGseJDHQ6cVa2EIWf3raa+NSwQSCMlHYU6qgfoZb2wWBjIKjoHV/Es+RWGbC8JtxYrNDomnLO6IQLtMSOjPSyZTAd93qKJyoMrH0tf+gxJpnxPn6LBFWzNXaYcZm/486rq+JFAD1PzoW7o=,iv:7nN6t7fGQ6xzHVBK0rtMTG409X5ngo2tkG8ULJHgKWI=,tag:pvw7fuvH3691z0lcyXGhaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
